/*
---------------------------------------------------------------------------------
File Name : PodiumConstants

Developer : vakea 
Email     : vakea@fluffici.eu
Real Name : Alex Guy Yann Le Roy

Date Created  : 15/07/2024
Last Modified : 15/07/2024

---------------------------------------------------------------------------------
*/

package eu.fluffici.bot.api.podium.impl;

import lombok.Getter;

/**
 * PodiumConstants is a class that defines the constants used for positioning elements in a podium.
 *
 * The class contains nested static classes for the first, second, and third places on the podium,
 * as well as additional nested static classes for user-specific details within each place.
 *
 * The constants within each class specify the X and Y coordinates, height, and width of the corresponding element.
 * These constants are used for positioning elements on the podium display.
 *
 * This class uses Lombok's @Getter annotation to generate accessor methods for all the fields.
 * Note that the accessor methods are not explicitly documented here, as they are automatically generated by Lombok.
 */
@Getter
public class PodiumConstants {
    private final String backgroundPath = "/assets/podium/podium_background.png";
    private final int titleX = 390;
    private final int titleY = 10;

    private final Logo logo = new Logo();
    private final FirstPlace firstPlace = new FirstPlace();
    private final SecondPlace secondPlace = new SecondPlace();
    private final ThirdPlace thirdPlace = new ThirdPlace();

    @Getter
    public static class Logo {
        private final String logoPath = "/assets/podium/branding.png";
        private final int X = 15;
        private final int Y = 10;
        private final int H = 252;
        private final int W = 74;
    }

    @Getter
    public static class FirstPlace {
        private final int X = 457;
        private final int Y = 88;
        private final int H = 65;
        private final int W = 65;

        private final User user = new User();

        @Getter
        public static class User {
            private final int avatarX = 442;
            private final int avatarY = 175;
            private final int avatarH = 95;
            private final int avatarW = 95;

            private final int nameX = 455;
            private final int nameY = 280;

            private final int countX = 452;
            private final int countY = 316;
        }
    }

    @Getter
    public static class SecondPlace {
        private final int X = 210;
        private final int Y = 128;
        private final int H = 65;
        private final int W = 65;

        private final SecondPlace.User user = new SecondPlace.User();

        @Getter
        public static class User {
            private final int avatarX = 195;
            private final int avatarY = 215;
            private final int avatarH = 95;
            private final int avatarW = 95;

            private final int nameX = 205;
            private final int nameY = 316;

            private final int countX = 205;
            private final int countY = 350;
        }
    }

    @Getter
    public static class ThirdPlace {
        private final int X = 687;
        private final int Y = 128;
        private final int H = 65;
        private final int W = 65;

        private final ThirdPlace.User user = new ThirdPlace.User();

        @Getter
        public static class User {
            private final int avatarX = 672;
            private final int avatarY = 215;
            private final int avatarH = 95;
            private final int avatarW = 95;

            private final int nameX = 683;
            private final int nameY = 316;

            private final int countX = 685;
            private final int countY = 350;
        }
    }
}